### ISSUE TITLE
Speaker discovery issue

### ISSUE THREAD

**Issue by hilli** [hilli/go-kef-w2#4]
Make speaker discovery more resilient.

```shell
 ~ % kefw2 config speaker discover --save
No speakers found
~ % kefw2 config speaker discover --save
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 1 [running]:
github.com/hilli/go-kef-w2/kefw2.(*KEFSpeaker).getId(0x14000031970)
	github.com/hilli/go-kef-w2/kefw2/kefw2.go:82 +0x3b0
github.com/hilli/go-kef-w2/kefw2.(*KEFSpeaker).UpdateInfo(0x14000031970)
	github.com/hilli/go-kef-w2/kefw2/kefw2.go:51 +0x9c
github.com/hilli/go-kef-w2/kefw2.NewSpeaker({0x14000175340?, 0x0?})
	github.com/hilli/go-kef-w2/kefw2/kefw2.go:35 +0x70
github.com/hilli/go-kef-w2/kefw2.DiscoverSpeakers()
	github.com/hilli/go-kef-w2/kefw2/discover.go:17 +0xa4
github.com/hilli/go-kef-w2/cmd/kefw2/cmd.init.func3(0x14000117100?, {0x101203e9a?, 0x4?, 0x101203e76?})
	github.com/hilli/go-kef-w2/cmd/kefw2/cmd/config_speaker.go:37 +0x70
github.com/spf13/cobra.(*Command).execute(0x1016e3560, {0x14000090920, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x1016e5ac0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/hilli/go-kef-w2/cmd/kefw2/cmd.Execute()
	github.com/hilli/go-kef-w2/cmd/kefw2/cmd/root.go:85 +0x58
main.main()
	./kefw2.go:27 +0x1c
```

- If no speakers are found, do not create an invalid config (If that's what's happening)
- Suggest adding speaker manually with `kefw2 config speaker add <IP>`

**Comment by hilli** [comment]
Should be done
