### ISSUE TITLE
Validate that the speaker is in the config when addressing it directly.

### ISSUE THREAD

**Issue by hilli** [hilli/go-kef-w2#5]
```shell
 ~ % kefw2 -s 192.168.1.25 status        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102a5a93c]

goroutine 1 [running]:
github.com/hilli/go-kef-w2/kefw2.(*KEFSpeaker).Source(0x14000031718?)
	github.com/hilli/go-kef-w2/kefw2/kefw2.go:143 +0x1c
github.com/hilli/go-kef-w2/cmd/kefw2/cmd.init.func18(0x102ffa360, {0x14000074a00?, 0x4?, 0x102b17e76?})
	github.com/hilli/go-kef-w2/cmd/kefw2/cmd/status.go:24 +0x34
github.com/spf13/cobra.(*Command).execute(0x102ffa360, {0x140000749e0, 0x2, 0x2})
	github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x102ff9ac0)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/hilli/go-kef-w2/cmd/kefw2/cmd.Execute()
	github.com/hilli/go-kef-w2/cmd/kefw2/cmd/root.go:85 +0x58
main.main()
```

Or maybe just let it work without having the speaker in the config, but do some pre validation on the target before coughing up stack traces. Could be useful in any case, should the speakers have moved IP.

**Comment by hilli** [comment]
Now works as expected without dumping trace.
